# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/common/typescript.gni")

transpile_web_ui("computer_use_ui") {
  output_module = false
  entry_points = [ [
        "computer_use",
        rebase_path("computer_use.tsx"),
      ] ]

  public_deps = [
    "//brave/components/computer_use/common:mojom_js",
    "//mojo/public/mojom/base",
  ]

  resource_name = "computer_use"
  imports_from = [ "//brave/components/computer_use/browser/resources/" ]
}

pack_web_resources("generated_resources") {
  resource_name = "computer_use"
  output_dir = "$root_gen_dir/brave/components/computer_use/browser/resources"
  deps = [ ":computer_use_ui" ]
}
