# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

source_set("n8n") {
  sources = [
    "mcp_client.cc",
    "mcp_client.h",
    "n8n_process_manager.cc",
    "n8n_process_manager.h",
    "n8n_process_manager_factory.cc",
    "n8n_process_manager_factory.h",
  ]

  deps = [
    "//base",
    "//brave/components/api_request_helper",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//content/public/browser",
    "//net",
    "//services/network/public/cpp",
    "//third_party/zlib/google:zip",
    "//url",
  ]
}
