# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

static_library("colibri") {
  visibility = [
    ":unit_tests",
    "//brave/browser:core",
    "//brave/browser/ai_chat/colibri",
    "//brave/browser/ui",
    "//brave/browser/ui/webui/ai_chat",
  ]

  sources = [
    "colibri_model_fetcher.cc",
    "colibri_model_fetcher.h",
    "colibri_service.cc",
    "colibri_service.h",
  ]

  deps = [
    "//base",
    "//brave/components/ai_chat/core/browser",
    "//brave/components/ai_chat/core/common",
    "//brave/components/ai_chat/core/common/mojom",
    "//components/keyed_service/core",
    "//components/prefs",
    "//mojo/public/cpp/bindings",
    "//net/traffic_annotation",
    "//services/network/public/cpp",
    "//url",
  ]

  public_deps = [ "//base" ]
}
